version: '3.8'

services:
  pagopa-ecommerce-watchdog-deadletter-service:
    container_name: pagopa-ecommerce-watchdog-deadletter-service
    build:
      dockerfile: "${DOCKER_FILE_NAME}"
      context: .
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - pagopa-ecommerce-watchdog-deadletter-service-net
  pagopa-ecommerce-helpdesk-service-mock:
    container_name: pagopa-ecommerce-helpdesk-service-mock
    volumes:
      - type: bind
        source: ./ecommerce-helpdesk-mock
        target: /config
        read_only: true
    build:
      context: .
      dockerfile: ecommerce-helpdesk-mock/Dockerfile.helpdesk-mock
    ports:
      - "3000:3000"
    networks:
      - pagopa-ecommerce-watchdog-deadletter-service-net

networks:
  pagopa-ecommerce-watchdog-deadletter-service-net:
    driver: bridge
