openapi: 3.0.3
info:
  title: 'Node technical support - API (local) ${service}'
  termsOfService: 'https://www.pagopa.gov.it/'
  version: 1.2.22-2-PIDM-1117-status-recovery'

servers:
  - url: '${host}/technical-support/nodo/api/v1'

tags:
  - name: Position Payment Snapshot Resource
    description: Operations on payment tokens snapshots

paths:
  /paymentToken/{paymentToken}:
    get:
      tags:
        - Position Payment Snapshot Resource
      parameters:
        - name: paymentToken
          in: path
          required: true
          schema:
            type: string
        - name: serviceIdentifier
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PositionPaymentSnapshotDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
        '500':
          description: Service unavailable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
  schemas:
    Instant:
      type: string
      format: date-time
      example: '2022-03-10T16:15:50Z'

    PositionPaymentSnapshotDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        pa_fiscal_code:
          type: string
        notice_id:
          type: string
        creditor_reference_id:
          type: string
        payment_token:
          type: string
        status:
          type: string
        inserted_timestamp:
          $ref: '#/components/schemas/Instant'
        updated_timestamp:
          $ref: '#/components/schemas/Instant'
        fk_position_payment:
          type: integer
          format: int64
        inserted_by:
          type: string
        updated_by:
          type: string

    ProblemJson:
      type: object
      properties:
        title:
          type: string
          description: A short, summary of the problem type.
        status:
          type: integer
          format: int32
          minimum: 100
          maximum: 600
          description: The HTTP status code generated by the origin server.
          example: 200
        details:
          type: string
          description: A human readable explanation specific to this occurrence of the problem.
          example: 'There was an error processing the request'

security:
  - ApiKeyAuth: []