FROM node:18.19.0-alpine@sha256:0085670310d2879621f96a4216c893f92e2ded827e9e6ef8437672e1bd72f437

WORKDIR /usr/src/app

RUN yarn global add json-server@0.17.4 --exact

EXPOSE 3000

CMD ["json-server", "/config/helpdesk.json", "--middlewares", "/config/middleware.js", "--routes", "/config/routes.json", "--host", "0.0.0.0"]