FROM node:alpine3.22@sha256:77f3c4d1f33c17dfa4af4b0add57d86957187873e313c2c37f52831d117645c8

WORKDIR /usr/src/app

RUN yarn global add json-server@0.17.4 --exact

EXPOSE 3000

CMD ["json-server", "/config/nodo-technical-support-server.json", "--routes", "/config/routes.json",  "--middlewares", "/config/middleware.js", "--host", "0.0.0.0"]
