FROM node:alpine3.22

WORKDIR /usr/src/app

RUN yarn global add json-server@0.17.4 --exact

EXPOSE 3000

CMD ["json-server", "/config/nodo-technical-support-server.json", "--routes", "/config/routes.json",  "--middlewares", "/config/middleware.js", "--host", "0.0.0.0"]
