FROM node:alpine3.22@sha256:6ff78d6d45f2614fe0da54756b44a7c529a15ebcaf9832fab8df036b1d466e73

WORKDIR /usr/src/app

RUN yarn global add json-server@0.17.4 --exact

EXPOSE 3000

CMD ["json-server", "/config/nodo-technical-support-server.json", "--routes", "/config/routes.json",  "--middlewares", "/config/middleware.js", "--host", "0.0.0.0"]
