microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: "pagopa-ecommerce-watchdog-deadletter-service"
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaecommercewatchdogdeadletterservice
    tag: "latest"
    pullPolicy: Always
  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 10
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 10
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weudev.ecommerce.internal.dev.platform.pagopa.it"
    path: /pagopa-ecommerce-watchdog-deadletter-service/(.*)
    servicePort: 8080
  serviceAccount:
    name: "ecommerce-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    ROOT_LOGGING_LEVEL: "info"
    OTEL_RESOURCE_ATTRIBUTES_DEPLOYMENT_ENVIRONMENT: "dev"
    OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    ECOMMERCE_HELPDESK_SERVER_URI: "https://api.platform.pagopa.it/ecommerce/helpdesk-service"
    ECOMMERCE_HELPDESK_SERVER_READ_TIMEOUT_MILLIS: "10000"
    ECOMMERCE_HELPDESK_SERVER_CONNECTION_TIMEOUT_MILLIS: "10000"
    NODO_TECHNICAL_SUPPORT_SERVER_URI: "https://api.dev.platform.pagopa.it/technical-support/ndp/api/v1"
    NODO_TECHNICAL_SUPPORT_SERVER_READ_TIMEOUT_MILLIS: "10000"
    NODO_TECHNICAL_SUPPORT_SERVER_CONNECTION_TIMEOUT_MILLIS: "10000"
    MONGO_HOST: pagopa-d-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-d-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    MONGO_DB_NAME: "ecommerce-watchdog"
    MONGO_MIN_POOL_SIZE: "0"
    MONGO_MAX_POOL_SIZE: "50"
    MONGO_MAX_IDLE_TIMEOUT_MS: "600000"
    MONGO_CONNECTION_TIMEOUT_MS: "2000"
    MONGO_SOCKET_TIMEOUT_MS: "10000"
    MONGO_SERVER_SELECTION_TIMEOUT_MS: "2000"
    MONGO_WAITING_QUEUE_MS: "2000"
    MONGO_HEARTBEAT_FREQUENCY_MS: "5000"
    MONGO_REPLICA_SET_OPTION: "&replicaSet=globaldb"
    AUTH_LOGIN_REDIRECT_URL: "https://weudev.ecommerce.internal.dev.platform.pagopa.it/pagopa-ecommerce-watchdog-deadletter-fe/"
    AUTH_JWT_VALIDITY_TIME_MINUTES: "1440"
    AUTH_JWT_SECRET_KEY_NAME: "watchdog-jwt-cert"
    AUTH_JWT_SECRET_KEY_PASSWORD: ""
    AUTH_AZURE_KV_ENDPOINT: "https://pagopa-d-ecommerce-kv.vault.azure.net/"
    AUTH_AZURE_MAX_RETRY: "3"
    AUTH_AZURE_RETRY_DELAY_MILLIS: "500"
  envSecret:
    MONGO_PASSWORD: mongo-ecommerce-password
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    ECOMMERCE_HELPDESK_API_KEY: ecommerce-helpdesk-service-api-key-for-watchdog
    NODO_TECHNICAL_SUPPORT_API_KEY: nodo-helpdesk-service-api-key-for-watchdog
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  secretProviderClass:
    create: true
  keyvault:
    name: "pagopa-d-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  azure:
    workloadIdentityClientId: "1be61b58-24e2-49c8-b401-89ebd004bf2e"
